<script>
    require(['jquery', 'carousel'], function($) {
        $('.product-carousel').owlCarousel({
            loop: true,
            responsiveClass: true,
            margin: 20,
            responsive: {
                0: {
                    items: 1
                },
                400: {
                    items: 2,
                    margin: 20
                },
                600: {
                    items: 3
                },
                800: {
                    items: 4
                },
                1100: {
                    items: 5
                },
                1350: {
                    items: 6
                }
            }
        })
    })
</script>
<?php
$productDetails = $block->getAllProducts();
?>

<section class="products-section">
    <div class="page-main">
        <div class="content-heading">
            <h2 class="title">MENS SHOES</h2>
        </div>
        <div class="block widget block-products-list grid">
            <div class="block-content">
                <div class="products-grid grid">
                    <ol class="product-items widget-product-grid owl-carousel owl-theme product-carousel">
                        <?php foreach ($productDetails as $product) : ?>
                            <li class="product-item">
                                <div class="product-item-info">
                                    <a href="<?= $product['url'] ?>" class="product-item-photo">
                                        <span class="product-image-container product-image-container-<?= $product['id'] ?>" style="width: 240px;">
                                            <span class="product-image-wrapper" style="padding-bottom: 125%;">
                                                <img class="product-image-photo" src="<?= $product['image'] ?>" loading="lazy" width="240" height="300" alt="<?= $product['name'] ?>">
                                            </span>
                                        </span>
                                    </a>
                                    <div class="product-item-details">
                                        <strong class="product-item-name">
                                            <a title="<?= $product['name'] ?>" href="<?= $product['url'] ?>" class="product-item-link">
                                                <?= $product['name'] ?>
                                            </a>
                                        </strong>
                                        <div class="price-box price-final_price" data-role="priceBox" data-product-id="<?= $product['id'] ?>" data-price-box="product-id-<?= $product['id'] ?>">
                                            <span class="old-price">
                                                <span>₹822.00</span>
                                            </span>
                                            <span class="normal-price">
                                                <span class="price-container price-final_price tax weee">
                                                    <span id="old-price-<?= $product['id'] ?>-widget-product-grid" data-price-amount="22" data-price-type="finalPrice" class="price-wrapper">
                                                        <span class="price"><?= '₹' . number_format($product['price'], 2) ?></span>
                                                    </span>
                                                </span>
                                            </span>
                                        </div>
                                        <div class="swatch-opt-1562" data-role="swatch-option-1562" data-rendered="true">
                                            <div class="swatch-attribute size" data-attribute-code="size" data-attribute-id="144"></div>
                                            <div class="swatch-attribute color" data-attribute-code="color" data-attribute-id="93">
                                                <div aria-activedescendant="" tabindex="0" aria-invalid="false" aria-required="true" role="listbox" aria-label="Color" class="swatch-attribute-options clearfix">
                                                    <?php foreach ($product['simple_products'] as $simpleProduct) : ?>
                                                        <div class="swatch-option color" id="option-label-color-93-item-<?php echo $simpleProduct['id']; ?>" index="<?php echo $simpleProduct['id']; ?>" aria-checked="false" aria-describedby="option-label-color-93" tabindex="0" data-option-type="1" data-option-id="<?php echo $simpleProduct['id']; ?>" data-option-label="<?php echo $simpleProduct['color']; ?>" aria-label="<?php echo $simpleProduct['color']; ?>" role="option" data-thumb-width="110" data-thumb-height="90" data-option-tooltip-value="<?php echo $simpleProduct['color']; ?>" style="background: <?php echo $simpleProduct['color']; ?> no-repeat center; background-size: initial;"></div>
                                                    <?php endforeach; ?>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="product-item-inner">
                                            <div class="product-item-actions">
                                                <div class="actions-primary">
                                                    <form data-role="tocart-form" data-product-sku="WS12" action="#" method="post">
                                                        <input type="hidden" name="product" value="1562">
                                                        <input type="hidden" name="uenc" value="aHR0cHM6Ly9tYWdlbnRvLm51Ymx1ZS5jby51ay9jaGVja291dC9jYXJ0L2FkZC91ZW5jL2FIUjBjSE02THk5dFlXZGxiblJ2TG01MVlteDFaUzVqYnk1MWF5OCUyQy9wcm9kdWN0LzE1NjIv">
                                                        <input name="form_key" type="hidden" value="njfb4cUiqt9DIdtW"> <button type="submit" title="Add to Cart" class="action tocart primary" data-product-id="<?php echo $product['id']; ?>">
                                                            <span>Add to Cart</span>
                                                        </button>
                                                        <input class="swatch-input super-attribute-select" name="super_attribute[144]" type="text" value="" data-selector="super_attribute[144]" data-validate="{required: true}" aria-required="true" aria-invalid="false"><input class="swatch-input super-attribute-select" name="super_attribute[93]" type="text" value="" data-selector="super_attribute[93]" data-validate="{required: true}" aria-required="true" aria-invalid="false">
                                                    </form>
                                                </div>
                                                <div class="actions-secondary" data-role="add-to-links">
                                                    <a href="#" class="action towishlist" data-action="add-to-wishlist" title="Add to Wish List" data-product-id="<?php echo $product['id']; ?>">
                                                        <span>Add to Wish List</span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        <?php endforeach; ?>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</section>