<?php
$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menu = $block->getHtml('level-top', 'submenu', $columnsLimit);
$currentUrl = $block->getCurrentUrl();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
?>

<nav class="navigation" role="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true,
        "position":{"my":"left top","at":"left bottom"}}}'>
        <li class="level0 home <?php if ($currentUrl == '/') : ?>active<?php endif; ?>"><a href="<?= /* @noEscape */ $storeManager->getStore()->getBaseUrl(); ?>" title="<?= /* @noEscape */ __('Home') ?>" class="level-top"><span><?= /* @noEscape */ __('Home') ?></span></a></li>
        <?= /* @noEscape */ $_menu; ?>
    </ul>
</nav>