 <script>
    require(['jquery', 'carousel'], function($) {
        $(document).ready(function() {
            $('.home-slider').owlCarousel({
                loop: true,
                nav: true,
                dots: false,
                items: 1,
                autoPlay: 2000,
            })
        });
    });
</script>
 <section class="slider-section">
     <div class="page-main">
         <div class="owl-carousel owl-theme home-slider">
             <div class="item">
                 <img href="#" src="<?php echo $block->getViewFileUrl('images/slider1.jpg') ?>" alt="slider1">
             </div>
             <div class="item">
                 <img href="#" src="<?php echo $block->getViewFileUrl('images/slider1.jpg') ?>" alt="slider1">
             </div>
             <div class="item">
                 <img href="#" src="<?php echo $block->getViewFileUrl('images/slider1.jpg') ?>" alt="slider1">
             </div>
         </div>
     </div>
 </section>
