
<div class="guarantee-divition">
    <div class="guarantee-content">
        <img src="<?php echo $block->getViewFileUrl('images/guarantee1.png') ?>" alt="guarantee">
        <p>100% ORIGINAL guarantee for
            all products at shopyshop.com</p>
    </div>
    <div class="guarantee-content">
        <img src="<?php echo $block->getViewFileUrl('images/guarantee2.png') ?>" alt="guarantee">
        <p>Return within 30 days
            of receiving your order</p>
    </div>         		
</div><div class="links">
    <div class="widget block block-static-block">
        <h4>About Us</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            sed do eiusmod tempor incididunt ut labore et dolore
            magna aliqua. Ut enim ad minim veniam, quis nostrud
            exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in
            voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        </p>
    </div>
</div>
<div class="footer links">
    <h4>Quick Access</h4>
    <ul>
        <li class="nav item"><a href="#">Fashion </a></li>
        <li class="nav item"><a href="#">Shoes </a></li>
        <li class="nav item"><a href="#">Mobile Phones </a></li>
        <li class="nav item"><a href="#">Bags </a></li>
        <li class="nav item"><a href="#">Body care </a></li>
        <li class="nav item"><a href="#">Electronics </a></li>
        <li class="nav item"><a href="#">New Arrival </a></li>
    </ul>
</div>
<div class="block newsletter">
        <div class="title"><strong>Connect with Us</strong></div>
        <ul class="social-media-icons">
            <li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/youtube.svg') ?>" alt="youtube"></a></li>
            <li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/facebook.svg') ?>" alt="facebook"></a></li>
            <li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/twitter.svg') ?>" alt="twitter"></a></li>
            <li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/instagram.svg') ?>" alt="instagram"></a></li>
            <li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/twitter.svg') ?>" alt="twitter"></a></li>
        </ul>
        <div class="title"><strong>Subscribe</strong></div>
        <div class="content">
            <p>Subscribe to stay tuned for new products and latest updates. Let's do it! </p>
            <form class="form subscribe" novalidate="novalidate" action="#" method="post" id="newsletter-validate-detail">
            <div class="field newsletter">
                <div class="control">
                    <label for="newsletter">
                    <span class="label">
                    Sign Up for Our Newsletter: </span>
                    <input name="email" type="email" id="newsletter" placeholder="" data-validate="{required:true, 'validate-email':true}">
                    </label>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary" title="Subscribe" type="submit" aria-label="Subscribe">
                <span>Subscribe</span>
                </button>
            </div>
            </form>
        </div>
    </div>